"""Roadmap generata da Raidho (Task Manager, TM11): con `"roadmap": "raidho"` in
.raidhowiki/config.json i tool roadmap di scrittura rispondono roadmap_read_only col
messaggio guida e non toccano il file; roadmap.list e il focus di session_start la
leggono ancora. Server MCP in un sottoprocesso (ROOT si legge all'import)."""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from _helpers import cov_env

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
SERVER_PATH = PLUGIN_ROOT / "scripts" / "mcp_memory_server.py"
PYTHON = os.environ.get("RAIDHO_TEST_PYTHON") or sys.executable

# come la scrive task/roadmap.py di Raidho (genera)
GENERATA = """---
title: Roadmap
type: roadmap
updated: 2026-10-05
roadmap_schema: 2
generated_by: raidho
---

# Roadmap

> Generated by Raidho from the project tasks: do not edit. Tasks change in the Task Manager
> (`raidho_team.py task ...` for team agents, or ask the Raidho orchestrator).

## Open

- [ ] (P0) RAI-7 Fix login | id: task-11111111111111111111111111111111 | est: 1h30min | owner: mario | added: 2026-10-01
- [~] (P1) RAI-8 Migrate token | id: task-22222222222222222222222222222222 | added: 2026-10-02

## Done

- [x] RAI-3 Old work | id: task-33333333333333333333333333333333 | added: 2026-09-20 | done: 2026-10-01

## Blocked

- [⏸] (P2) RAI-9 Hub backup | id: task-44444444444444444444444444444444 | added: 2026-10-03
"""

SCRITTURE = {
    "roadmap.add": {"title": "nuovo", "priority": "P1"},
    "roadmap.update": {"id": "task-11111111111111111111111111111111", "title": "cambiato"},
    "roadmap.complete": {"id": "task-11111111111111111111111111111111"},
    "roadmap.block": {"id": "task-22222222222222222222222222222222", "reason": "x"},
    "roadmap.archive": {"older_than_days": 0},
}


def _progetto(tmp_path: Path, flag) -> tuple[Path, dict]:
    project = tmp_path / "proj"
    wiki = project / ".raidhowiki" / "wiki"
    wiki.mkdir(parents=True)
    (wiki / "roadmap.md").write_text(GENERATA, encoding="utf-8")
    if flag is not None:
        (project / ".raidhowiki" / "config.json").write_text(
            flag if isinstance(flag, str) else json.dumps(flag), encoding="utf-8")
    env = {"RAIDHO_SCOPE": "project", "RAIDHO_ROOT": str(project), "RAIDHO_WIKI_EMBED": "0",
           "PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": str(tmp_path), **cov_env()}
    return project, env


def _rpc(env: dict, calls: list[tuple[str, dict]]) -> list:
    msgs = [{"jsonrpc": "2.0", "id": 1, "method": "initialize",
             "params": {"protocolVersion": "2024-11-05", "capabilities": {}, "clientInfo": {"name": "t", "version": "1"}}},
            {"jsonrpc": "2.0", "method": "notifications/initialized"},
            {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}]
    proc = subprocess.run([PYTHON, str(SERVER_PATH)], input="\n".join(json.dumps(m) for m in msgs) + "\n",
                          capture_output=True, text=True, env=env, timeout=90)
    tools = {}
    for line in proc.stdout.splitlines():
        if line.startswith("{") and json.loads(line).get("id") == 2:
            tools = {t["name"] for t in json.loads(line)["result"]["tools"]}
    wire = {n: next(w for w in tools if w.replace("_", ".") == n.replace("_", ".")) for n, _ in calls}
    for i, (nome, args) in enumerate(calls, start=3):
        msgs.append({"jsonrpc": "2.0", "id": i, "method": "tools/call",
                     "params": {"name": wire[nome], "arguments": args}})
    proc = subprocess.run([PYTHON, str(SERVER_PATH)], input="\n".join(json.dumps(m) for m in msgs) + "\n",
                          capture_output=True, text=True, env=env, timeout=90)
    assert proc.returncode == 0, proc.stderr[-2000:]
    risposte = {}
    for line in proc.stdout.splitlines():
        if line.startswith("{"):
            d = json.loads(line)
            if "id" in d:
                risposte[d["id"]] = d
    out = []
    for i in range(3, 3 + len(calls)):
        r = risposte[i]
        assert "result" in r, r
        out.append(json.loads(r["result"]["content"][0]["text"]))
    return out


def test_scritture_in_sola_lettura_col_flag(tmp_path):
    project, env = _progetto(tmp_path, {"embedding": {"provider": "mock"}, "roadmap": "raidho"})
    risposte = _rpc(env, [*SCRITTURE.items(), ("roadmap.list", {})])
    for nome, r in zip(SCRITTURE, risposte):
        assert r.get("code") == "roadmap_read_only", (nome, r)
        assert "raidho_team.py task" in r["error"] and "orchestrator" in r["error"], r
    # il file non cambia e nessun backup/archivio
    assert (project / ".raidhowiki" / "wiki" / "roadmap.md").read_text(encoding="utf-8") == GENERATA
    assert sorted(p.name for p in (project / ".raidhowiki" / "wiki").iterdir()) == ["roadmap.md"]
    lista = risposte[-1]
    assert "error" not in lista, lista
    assert {t["id"] for t in lista["tasks"]} == {f"task-{c * 32}" for c in "1234"}
    assert lista["summary"]["in_progress"] == 1 and lista["summary"]["blocked"] == 1


@pytest.mark.parametrize("flag", [None, {"roadmap": "plugin"}, {"roadmap": "Raidho "}, ["roadmap", "raidho"],
                                  "{non json", '"raidho"'])
def test_senza_flag_si_scrive(tmp_path, flag):
    project, env = _progetto(tmp_path, flag)
    [r] = _rpc(env, [("roadmap.add", {"title": "nuovo", "priority": "P1"})])
    assert "error" not in r, r
    assert "nuovo" in (project / ".raidhowiki" / "wiki" / "roadmap.md").read_text(encoding="utf-8")


def test_session_start_legge_la_generata(tmp_path):
    project, _ = _progetto(tmp_path, {"roadmap": "raidho"})
    spec = importlib.util.spec_from_file_location("session_start_tm11", PLUGIN_ROOT / "hooks" / "session_start.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    righe = mod._load_roadmap_focus(project / ".raidhowiki" / "wiki")
    testo = "\n".join(righe)
    assert "[P0] task-11111111111111111111111111111111 — RAI-7 Fix login (1h30min) @mario" in testo
    assert "[~] task-22222222222222222222222222222222 — RAI-8 Migrate token" in testo
    assert "Old work" not in testo and "Hub backup" not in testo


def test_comando_raidho_task_solo_list_e_triage():
    testo = (PLUGIN_ROOT / "commands" / "raidho-task.md").read_text(encoding="utf-8")
    assert '"roadmap": "raidho"' in testo
    assert "list" in testo and "triage" in testo
